### ISSUE TITLE
Question about pre-trained models

### ISSUE THREAD

**Issue by leannmlindsey** [Zhihan1996/DNABERT_2#1]
Hello! Congratulations on your work.  I was so happy to see this come out!

I have a question about running the GUE tests according to your instructions.  In DNABERT1 you had to physically download the pre-trained model.  It seems from looking at the code that now the models are hosted at huggingface and I do not need to download the pre-trained models to run these tests.  Is that correct?

My goal is to do some further pre-training with bacterial datasets starting from a pre-trained model.  To do this, would I load your pre-trained model as a checkpoint and then run a script similar to the pretraining script from DNABERT1?

Thanks for any help you can provide and again, great work!

LeAnn

**Comment by Zhihan1996** [comment]
Hi, 

Thanks for your interests in our works!

Yes, now both the DNABERT-1 and DNABERT-2 are hosted at [huggingface modelhub](https://huggingface.co/zhihan1996). You can either manually download the checkpoints if need or simply access them with:

```
from transformers import AutoModel

model = AutoModel.from_pretrained("zhihan1996/DNABERT-2-117M")
```

And for further pre-training, you are correct! The simplest way of doing this for now is using the huggingface official example `run_mlm.py` as provided here https://github.com/huggingface/transformers/tree/main/examples/pytorch/language-modeling, and run some commands like:

```
python run_mlm.py \
    --model_name_or_path zhihan1996/DNABERT-2-117M \
    --train_file path_to_train_file \
    --validation_file path_to_validation_file \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --output_dir /tmp/test-mlm
```

**Comment by leannmlindsey** [comment]
Thank you so much for your quick reply.
