### ISSUE TITLE
环境问题一直报错，不知道什么原因，因为使用您给的指令安装的环境全都是最新的，我也这样尝试过，还是不行，可以帮忙解答下么，邮箱1640472053@qq.com

### ISSUE THREAD

**Issue by duqimeng** [Zhihan1996/DNABERT_2#10]
![image](https://github.com/Zhihan1996/DNABERT_2/assets/77875733/9dd66bb2-b46d-461e-af0a-7b63fcfba639)

**Comment by Zhihan1996** [comment]
Hey,

Can you please first try to deactivate the flash attention module by `pip uninstall triton`?
