### ISSUE TITLE
Functional variants identification with DNABERT-2

### ISSUE THREAD

**Issue by Shicheng-Guo** [Zhihan1996/DNABERT_2#13]
Dear Zhihan, 

Thank you for the great contribution to the Genome Foundation Model filed. I am quite interested in the Functional variants identification with DNABERT-2 section. However, I am not so sure about the "predicted high-attention regions" is from pre-training model or fine-tuning model. if it is fine-tuning model, which sub-task it is from? 

We applied DNABERT to identify functional variants using around 700 million short variants in dbSNP([Sherry, 2001]. Specifically, we selected only those variants that are located **inside DNABERT predicted high-attention regions** and repeated the predictions, using sequences with altered alleles.

Thanks. 

Shicheng

I think I get the point now. It is from fine-tuning stage.

**Comment by Zhihan1996** [comment]
Hey,

Thanks for your question. I think my collaborator @jerryji1993 would be a more appropriate person for this question.
