### ISSUE TITLE
Redundancy in the code and has issues

### ISSUE THREAD

**Issue by Sudhendra** [Zhihan1996/DNABERT_2#14]
Hey, 

Congrats on your contribution but the code isn't properly written. It might be that at the time of training for you, it must've worked but now, there are some severe issues. Please don't get me wrong, I hope you fix them or give me an opportunity to contribute to fix it.

**The key issues with DNABERT-2**
1. ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 3168) + inhomogeneous part. 
2. The .sh keeps going even after the error prompt (bad designing of the code).
3. The training somehow stops in between and the code jumps to evaluation where the above shown ValueError occurs.
4. There is no epoch tracking. This makes it extremely un-informative of the progress. 

Are you planning to fix these issues? Thanks for the huggingface model btw. That seems to be working a ok!

**Comment by Zhihan1996** [comment]
Hey,

Thanks for sharing the issues. I haven't find time to fully test all the codes and scripts. Please feel free to create pull requests if you have any idea in polishing the code base. Thanks!
