### ISSUE TITLE
Embedding long sequences

### ISSUE THREAD

**Issue by fteufel** [Zhihan1996/DNABERT_2#2]
Hi,

Thanks for making DNABERT2 available!

I want to prepare embeddings of potentially long sequences for downstream use. How would you recommend I do that?

A) Taking the sequence as-is and embedding all at once ( I guess it is technically possible with ALiBi ?)
B) Chunking the sequence into smaller pieces as done for pretraining, and then concatenating the embeddings (128 nucleotides or 128 BPE tokens? Not sure)

Would appreciate your help!

**Comment by Zhihan1996** [comment]
Hi,

Thanks for your interests in our work!

I think it depends on the length of your sequence. In general, if it's not extra-long (e.g., less than 10000), I think method A should works well, otherwise, you may split it into pieces and concatenate/average the embeddings.
