### ISSUE TITLE
Error about inconsistent config_class when loading model

### ISSUE THREAD

**Issue by meganbkratz** [Zhihan1996/DNABERT_2#22]
Hi,

Thank you so much for updating DNABERT!!! 

I'm running into the following error both on the command line and when I try to run the scripts/run_dnabert2.sh script. Do you have any insight into what's going wrong here?

Here's the command line version:
```
Python 3.8.17 (default, Jul  5 2023, 21:04:15) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from transformers import AutoTokenizer, AutoModel
>>> tokenizer = AutoTokenizer.from_pretrained("zhihan1996/DNABERT-2-117M", trust_remote_code=True)
>>> model = AutoModel.from_pretrained("zhihan1996/DNABERT-2-117M", trust_remote_code=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nas/longleaf/home/mkratz/.conda/envs/dna/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
    cls.register(config.__class__, model_class, exist_ok=True)
  File "/nas/longleaf/home/mkratz/.conda/envs/dna/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 513, in register
    raise ValueError(
ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'transformers.models.bert.configuration_bert.BertConfig'> and you passed <class 'transformers_modules.zhihan1996.DNABERT-2-117M.5fd206e1a13cee3ef4a608677312175eb6f8143d.configuration_bert.BertConfig'>. Fix one of those so they match!
```

Thanks!!!

**Comment by leannmlindsey** [comment]
I also had this same error when I was doing the "quick start" section in the README

**Comment by meganbkratz** [comment]
This error seems to be related to having a newer version of transformers.

It resolved for me when I switched from transformers version 4.31.0 (the current version) to transformers version 4.28.0 (the version in the generation_config.json file of the model).

**Comment by joseacitores** [comment]
You can solve this error by loading the config first and then creating the model from the config

`config = BertConfig.from_pretrained("zhihan1996/DNABERT-2-117M")
model = AutoModel.from_config(config)`

This solved it for me

**Comment by Zhihan1996** [comment]
Hey,

Thank you for providing the solutions! I have updated the `requirements.txt` file to specify the `transformers` version I used. It should be fine now.

**Comment by nongiga** [comment]
@Zhihan1996 @joseacitores this is the wrong solution. When you load "from_config" you're not loading the model weights. https://github.com/huggingface/transformers/issues/4685#issuecomment-636306895
