### ISSUE TITLE
Which license is applied for DNABERT2 

### ISSUE THREAD

**Issue by Shicheng-Guo** [Zhihan1996/DNABERT_2#23]
Dear Zhihan, 

Which license is applied for DNABERT2 , Apache 2.0 License or any other versions? 

Thanks. 

Shicheng

**Comment by colindaven** [comment]
Yes, this is a critical aspect. No license implies no allowed use. A MIT or GPL2 license would be very permissive if you're not into licenses. Thanks.

**Comment by yguoma** [comment]
Please see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

"without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. "

**Comment by Zhihan1996** [comment]
Hey @yguoma @Shicheng-Guo @colindaven , thanks for pointing out the License issue. After some research, I plan to apply the`Apache License 2.0` for this project and have updated the `LICENSE` file accordingly.
