### ISSUE TITLE
Error while loading the model

### ISSUE THREAD

**Issue by sumanth2002629** [Zhihan1996/DNABERT_2#29]
Thanks for the implementation of DNABERT, I had a small issue, could you please fix it?

`model = AutoModel.from_pretrained("zhihan1996/DNABERT-2-117M", trust_remote_code=True)` when I run this I am getting the following error. Any idea how to fix it??

ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has  and you passed . Fix one of those so they match!

**Comment by smruti241** [comment]
@sumanth2002629 I am getting the same issue

**Comment by Zhihan1996** [comment]
Hey,

Can you please try `pip install transformers==4.29`?

This should solve the problem.
