### ISSUE TITLE
lora_target_modules default wrong

### ISSUE THREAD

**Issue by Vejni** [Zhihan1996/DNABERT_2#3]
Hi, 

Thanks a lot for uploading DNABERT2. 
I have noticed a small mistake when using lora, the default lora_target_modules ["query", "value"] do not seem to be correct. Through trial and error ["q", "v"] worked for me.

**Comment by Zhihan1996** [comment]
Hi,

Thank you very much for identifying this! This actually depends on the naming of layers in each model. The best way is to load and print model layer names before setting this parameter. Will update the README soon to explains more on this. Thanks!
