### ISSUE TITLE
Evaluate models on GUE: How to evaluate on our own dataset.

### ISSUE THREAD

**Issue by smruti241** [Zhihan1996/DNABERT_2#33]
Hi @Zhihan1996, I must say it is an excellent work.
I was going through the GUE and their dataset. I have covid data, I want to finetune it. Can you please tell me how can I do it? Because DNABERT-2 has covid data in it, so it would be really helpful for me. Thanks!

**Comment by Zhihan1996** [comment]
Please follow the section 6.2 on README.md to do this.
