### ISSUE TITLE
Facing issue while computing embeddings

### ISSUE THREAD

**Issue by smruti241** [Zhihan1996/DNABERT_2#34]
I have used the code for computing embeddings. But it is showing the error.
dna = "ACGTAGCATCGGATCTATCTATCGACACTTGGTTATCGATCTACGAGCATCTCGTTAGC"
inputs = tokenizer(dna, return_tensors = 'pt')["input_ids"]
hidden_states = model(inputs)[0] # [1, sequence_length, 768]

# embedding with mean pooling
embedding_mean = torch.mean(hidden_states[0], dim=0)
print(embedding_mean.shape) # expect to be 768

# embedding with max pooling
embedding_max = torch.max(hidden_states[0], dim=0)[0]
print(embedding_max.shape) # expect to be 768

after running this piece of code, I got error:
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[<ipython-input-6-287a01333466>](https://localhost:8080/#) in <cell line: 3>()
      1 dna = "ACGTAGCATCGGATCTATCTATCGACACTTGGTTATCGATCTACGAGCATCTCGTTAGC"
      2 inputs = tokenizer(dna, return_tensors = 'pt')["input_ids"]
----> 3 hidden_states = model(inputs)[0] # [1, sequence_length, 768]
      4 
      5 # embedding with mean pooling

12 frames
[~/.cache/huggingface/modules/transformers_modules/zhihan1996/DNABERT-2-117M/81ac6a98387cf94bc283553260f3fa6b88cef2fa/flash_attn_triton.py](https://localhost:8080/#) in _flash_attn_forward(q, k, v, bias, causal, softmax_scale)
    779     assert q.dtype in [torch.float16,
    780                        torch.bfloat16], 'Only support fp16 and bf16'
--> 781     assert q.is_cuda and k.is_cuda and v.is_cuda
    782     softmax_scale = softmax_scale or 1.0 / math.sqrt(d)
    783 

AssertionError:

Please let me know what should I do?

**Comment by Zhihan1996** [comment]
Can you try to install triton with `pip install triton==2.0.0.dev20221202`? Or for simplicity, you may disable triton with `pip uninstall triton`
