### ISSUE TITLE
Error when Loading DNABERT Model using `AutoModel`

### ISSUE THREAD

**Issue by aaronmaiww** [Zhihan1996/DNABERT_2#35]
**Issue:** 

I am trying to load a pretrained DNABERT model from the model hub using the `AutoModel` and `AutoTokenizer` classes from the `transformers` library. However, I am encountering an error related to inconsistent `config_class` attributes.

**Code to Reproduce:**
```python
from transformers import AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("zhihan1996/DNABERT-2-117M", trust_remote_code=True)
model = AutoModel.from_pretrained("zhihan1996/DNABERT-2-117M", trust_remote_code=True)
```

**Error Message:**
```
ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'transformers.models.bert.configuration_bert.BertConfig'> and you passed <class 'transformers_modules.zhihan1996.DNABERT-2-117M.81ac6a98387cf94bc283553260f3fa6b88cef2fa.configuration_bert.BertConfig'>. Fix one of those so they match!
```

**Environment Details:**
- Python version: 3.10
- OS: Windows11

---

**Comment by Zhihan1996** [comment]
Can you try `pip install transformers==4.29` ? This  should solve the problem.
