### ISSUE TITLE
Issue regarding the config_class 

### ISSUE THREAD

**Issue by sai-kiran7** [Zhihan1996/DNABERT_2#38]
ValueError                                Traceback (most recent call last)
[<ipython-input-5-5e6189d49f0f>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model = AutoModel.from_pretrained("zhihan1996/DNABERT-2-117M", trust_remote_code=True)

1 frames
[/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py](https://localhost:8080/#) in register(cls, config_class, model_class, exist_ok)
    534         """
    535         if hasattr(model_class, "config_class") and model_class.config_class != config_class:
--> 536             raise ValueError(
    537                 "The model class you are passing has a `config_class` attribute that is not consistent with the "
    538                 f"config class you passed (model has {model_class.config_class} and you passed {config_class}. Fix "

ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'transformers.models.bert.configuration_bert.BertConfig'> and you passed <class 'transformers_modules.zhihan1996.DNABERT-2-117M.81ac6a98387cf94bc283553260f3fa6b88cef2fa.configuration_bert.BertConfig'>. Fix one of those so they match!

Can you please help me out

**Comment by akd13** [comment]
You need to use `transformers==4.29.0`

**Comment by sai-kiran7** [comment]
Thank you @akd13 now the above issue is resolved

**Comment by sai-kiran7** [comment]
@akd13  can you help me out in understanding the below point more clearly 

Some weights of BertModel were not initialized from the model checkpoint at zhihan1996/DNABERT-2-117M and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

**Comment by Zhihan1996** [comment]
Hey @akd13, thanks for the response.

Hey @sai-kiran7, this basically means some of the parameters in the model you are currently using does not exist in the pre-trained checkpoint. This is because the `bert.pooler` layer are used for transforming the last hidden state of the `[CLS]` token, and in our pre-training stage, we do not have any training target that relates to `[CLS]`. So we do not need the `bert.pooler` layer in the pre-training stage.
