### ISSUE TITLE
GUE: Splice site recognition in regards to sequence labeling/NER vs classification

### ISSUE THREAD

**Issue by immanuelazn** [Zhihan1996/DNABERT_2#39]
Hi Zhihan,  

Hope you're doing well.  I had a wonderful time reading your paper in regards to the improvements made to DNABERT and trying to set up a language model evaluation framework.  

However, I question whether the labels for the splice site recognition benchmark truly represents how a user may approach this task.  When going through the train/dev/test set, I've noticed that your labels only provide an annotation on whether the entire sequence is {no splice site, donor, acceptor}.  Current state of the art tools, such as SpliceAI, provide even further information similar to an NER task by labeling every nucleotide within a given sequence. Therefore, has DNABERT2 been previously evaluated in evaluating Splice sites as an NER task?

**Comment by Zhihan1996** [comment]
Hey,

Thanks for pointing out this! This is a great point but we have not tried to evaluate splice sites as an NER task. I will add it to my TODO list!

**Comment by immanuelazn** [comment]
No problem, let me know if you need help sourcing an appropriate train/val/test dataset for GUE. Best of luck!
