### ISSUE TITLE
Update requirements with version numbers

### ISSUE THREAD

**Issue by Vejni** [Zhihan1996/DNABERT_2#4]
Hi,

I just wanted to note that installing the requirements.txt in a clean environment leads to versions which are not compatible, leading to errors with triton. Installing "some" of the versions listed in this [discussion](https://huggingface.co/mosaicml/mpt-7b-storywriter/discussions/10) helped for me.

Thanks again for your work!

**Comment by Zhihan1996** [comment]
Hi,

Thanks for sharing this! Will figure out it soon.
