### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by wych1994** [Zhihan1996/DNABERT_2#45]
Hi, I tried to first time run the finetunning with train.py. I had an error at the following lines:
parser = transformers.HfArgumentParser((ModelArguments, DataArguments, TrainingArguments))
model_args, data_args, training_args = parser.parse_args_into_dataclasses()

Below is the error message I got:
```plaintext
  ValueError: (Field(name=None,type=None,default='steps',default_factory=<dataclasses._MISSING_TYPE object at 0x0000016635086850>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),_field_type=None),) is not a valid IntervalStrategy
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "C:\ProgramData\MiniConda\envs\dnabert\lib\enum.py", line 670, in __new__
      raise exc
    File "C:\ProgramData\MiniConda\envs\dnabert\lib\enum.py", line 653, in __new__
      result = cls._missing_(value)
    File "C:\ProgramData\MiniConda\envs\dnabert\lib\site-packages\transformers\utils\generic.py", line 348, in _missing_
      raise ValueError(
  ValueError: (Field(name=None,type=None,default='steps',default_factory=<dataclasses._MISSING_TYPE object at 0x0000016635086850>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),_field_type=None),) is not a valid IntervalStrategy, please select one of ['no', 'steps', 'epoch']
```

Any idea to fix that?
Thank you!

**Comment by Zhihan1996** [comment]
Can you try to install `transformers` with `pip install transformers==4.29`?

**Comment by wych1994** [comment]
Unfortunately, I downgraded ```transformer``` package from 4.29.2 to 4.29.0 and I got the same error.
I am using Windows 11 and PyCharm IDE.
To reproduce the error, I initialized a new conda environment and did the following installation steps:
```
conda create -n dna python=3.8
conda activate dna
python3 -m pip install -r requirements.txt
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
```
Additionally, the error pop at the following line in the ```train``` function at ```train.py```:
```
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
```
I also tried to upgrate ```transformer``` to latest but it did work and with new errors.

**Comment by Zhihan1996** [comment]
Thanks for sharing! This is expected if you run the codes from the IDE. This argument parser is designed for running code from the command line. Can you try to run it in command line?

**Comment by sy0217** [comment]
sorry, I met the same situation and error code. Could you tell me how to fix the issue?  Thanks

**Comment by Zhihan1996** [comment]
Are yor running the codes from an interactive python interpreter (e.g., Jupyter Notebook or IPython). The `argparse` package is expected to be run from the command line
