### ISSUE TITLE
human vs non-human data ratio

### ISSUE THREAD

**Issue by Shicheng-Guo** [Zhihan1996/DNABERT_2#5]
Dear Zhihan,

I am curious is there any evaluation to identify the best ratio for human vs non-human data? GENA-LM model included human T2T and 1000 Genome project to make human vs non-human equal to 1:1. 

I am wondering how you think about this ratio when you develop this project/model. 

Thanks. 

Shicheng

**Comment by Zhihan1996** [comment]
Hi,

Thanks for your interests in our work! 

I think this is a interesting question that I cannot answer without throughout empirical analysis. In DNABERT-2, the human vs non-human ratio is roughly 1:9, which still give the model good compatibility on human genome tasks.  But we haven't conducted any experiments on how the model performance changes as the ratios changes. I think this question itself is a very interesting research topic in this domain, quite straightforward yet computational expensive.
