### ISSUE TITLE
Pre-training Data

### ISSUE THREAD

**Issue by leannmlindsey** [Zhihan1996/DNABERT_2#51]
In the paper you state, "In order to facilitate further research on large-scale genome foundational models, we have collated and made available multi-species genome datasets for both pre-training of models (Sec. 4.1) and benchmarking (Sec. 4.2)."

but I cannot see where these datasets are, I have looked both on Huggingface and your github?  

Have I overlooked them somewhere?

**Comment by Zhihan1996** [comment]
Sorry for the confusion. I will organize the data are share it soon. Will let you know when it's ready.
