### ISSUE TITLE
ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed

### ISSUE THREAD

**Issue by rohan-sonthalia** [Zhihan1996/DNABERT_2#55]
I get the following error when I try to use the pre-trained DNABERT-2 on hugging face, through the transformers package

`ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'transformers.models.bert.configuration_bert.BertConfig'> and you passed <class 'transformers_modules.zhihan1996.DNABERT-2-117M.1d020b803b871a976f5f3d5565f0eac8f2c7bb81.configuration_bert.BertConfig'>. Fix one of those so they match!`

**Comment by colobas** [comment]
Can you share how you addressed this?
