### ISSUE TITLE
Downstream Association Study

### ISSUE THREAD

**Issue by Shicheng-Guo** [Zhihan1996/DNABERT_2#6]
Hi Zhihan, 

I am wondering what do you think about the downstream association study to identify phenotype associated variants/regions in Genome Foundation Model. Do you think current model is suitable for such task or not? if not, is there any comments on how to develop a good model for such task. 

Thanks

Shicheng

**Comment by Zhihan1996** [comment]
Hey,

Thanks for your question. I think my collaborator @jerryji1993 would be a more appropriate person for this question.
