### ISSUE TITLE
attention maps (DNABERT-viz) are generated during the pretraining stage or the fine-tuning stage

### ISSUE THREAD

**Issue by Shicheng-Guo** [Zhihan1996/DNABERT_2#7]
Dear Zhihan,

Thank you so much for the great contribution to the filed to develop this awesome pretraining model. The manuscript doesn't explicitly mention whether the attention maps (DNABERT-viz) are generated during the pretraining stage or the fine-tuning stage. Could you please more some explicitly explanation?

Thanks.

Shicheng

**Comment by Zhihan1996** [comment]
Hi Shicheng,

The attention map can be generated from any trained model checkpoint. You can either generate from the pre-trained model or fine-tune the model on a specific task before generating the attention map. In general, I think the second way is better if you are interested in a particular task.
