### ISSUE TITLE
ALiBi not working

### ISSUE THREAD

**Issue by fteufel** [Zhihan1996/DNABERT_2#9]
Hi, I tried following the README with 
```python
from transformers import AutoModel, AutoTokenizer

# Load the model and tokenizer
model = AutoModel.from_pretrained("zhihan1996/DNABERT-2-117M")
tokenizer = AutoTokenizer.from_pretrained("zhihan1996/DNABERT-2-117M")
```

This does not work correctly with ALiBi, as it doesn't use the model class defined at https://huggingface.co/zhihan1996/DNABERT-2-117M/blob/main/bert_layers.py
Rather, it uses the default Huggingface BERT class, which, if I understand it correctly, does not have the ALiBI utils such as `rebuild_alibi_tensor`. 

I encountered the error by trying to run a sequence longer than 512. Should the model be loaded another way to reproduce it correctly?

**Comment by Zhihan1996** [comment]
Hey,

I am sorry that the commands in README is incorrect. Will update it soon. Please try

```
import torch
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("zhihan1996/DNABERT-2-117M", trust_remote_code=True)
model = AutoModel.from_pretrained("zhihan1996/DNABERT-2-117M", trust_remote_code=True)
```
